# Configuração do Nginx para o subdiretório /clientes/
# Copie e cole este bloco dentro do bloco "server" da sua configuração do Nginx.

location /clientes {
    alias /caminho/para/seus/arquivos/dist/app/browser; # Altere para o caminho absoluto no seu servidor
    try_files $uri $uri/ /clientes/index.html;
}
